import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

class ConsistencyValidator:
    @staticmethod
    def validate_consistency(module_name: str, module_output: Dict[str, Any], canonical_obj: Dict[str, Any]) -> bool:
        """
        Validates that the output generated by a module (KPIs, metrics) aligns
        precisely with the values in the canonical DatasetAnalysisObject.
        """
        canonical_kpis = canonical_obj.get("kpis", {})
        
        # Verify Dashboard / Analytics KPIs
        if module_name == "Dashboard" or module_name == "Analytics":
            module_kpis = module_output.get("kpis", {})
            for key, val in module_kpis.items():
                if key in canonical_kpis:
                    # Allow slight float precision difference
                    if isinstance(val, (int, float)) and isinstance(canonical_kpis[key], (int, float)):
                        if abs(val - canonical_kpis[key]) > 0.01:
                            logger.error(f"Consistency mismatch in {module_name} for KPI '{key}': {val} vs canonical {canonical_kpis[key]}")
                            return False
                    elif val != canonical_kpis[key]:
                        logger.error(f"Consistency mismatch in {module_name} for KPI '{key}': {val} vs canonical {canonical_kpis[key]}")
                        return False

        # Verify Consultant Report Score and Status
        elif module_name == "BusinessConsultant" or module_name == "Consultant":
            health_score = module_output.get("health_score")
            canonical_score = canonical_obj.get("kpis", {}).get("dataset_health_score", 100.0)
            if health_score is not None and abs(health_score - canonical_score) > 0.01:
                logger.error(f"Consistency mismatch in Consultant Health Score: {health_score} vs canonical {canonical_score}")
                return False

        # Verify Forecast points and columns
        elif module_name == "MLForecast" or module_name == "Forecast":
            target = module_output.get("target_column")
            measures = canonical_obj.get("schema_metadata", {}).get("numerical_measures", [])
            if target and target not in measures:
                logger.error(f"Consistency mismatch in Forecast target column: '{target}' is not in detected measures {measures}")
                return False

        logger.info(f"Consistency check passed for module '{module_name}'.")
        return True
